### ISSUE TITLE
Unsupported binary operator `StringConcat`

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-ballista#201] opened 2022-09-10 22:16 UTC
**Describe the bug**
```
Could not parse logical plan protobuf: Error during planning: General error: Unsupported binary operator '\\\"StringConcat\\\"
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by askoa** [comment] 2022-09-11 00:26
I think a possible fix is to include a function like [from_str](https://stackoverflow.com/a/61948093) in `arrow-datafustion#Operator` and use it in `arrow-ballista`. I see that `ballista`'s code has not included Bitwise operators too. This issue will resurface whenever a new binary operator is included in `datafusion` project. Including the `from_str` function will ensure two projects need not be modified when a binary operator is included.

**Comment by askoa** [comment] 2022-09-14 19:26
@andygrove Sorry for being little late for the party. My impression of the ticket was that the error quoted in the issue description is generated in the function [`from_proto_binary_op`](https://github.com/apache/arrow-ballista/blob/23f8cad74de7d3e08b202eb8c086083586d4511c/ballista/rust/core/src/serde/mod.rs#L199). To fix the issue,  `StringConcat` has to be added to the `match op` block in that function. 

I also see there might be more issues in future, now that Bitwise operators are included in the `Operator` which is not yet added to the `match op` block. I wrote an [earlier comment](https://github.com/apache/arrow-ballista/issues/201#issuecomment-1242826089) that rather than keep updating the `match op` block in arrow-ballista project, its better to include a `from_str` function in the `arrow-datafusion` project. 

I see that the issue is closed without updating `match op` block. It would be great to know how the issue is fixed without updating the `match op` block. Could you please explain?

**Comment by andygrove** [comment] 2022-09-14 22:04
Hi @askoa. The bug that I fixed was related to logical plan serialization. This is part of the `datafusion-proto` crate that Ballista uses. You are right though .. we also need to fix this in the physical plan serialization.

**Comment by andygrove** [comment] 2022-09-14 22:15
@askoa, I created a PR to add the missing operators, but I agree with your comments that we could leverage DataFusion rather than have duplicate code here. DataFusion has a `from_proto_binary_op` that we could use, but it is currently private.

We also need some tests in Ballista around this.

**Comment by askoa** [comment] 2022-09-14 22:17
@andygrove Thanks for the response. I'll pick this one up.

**Closed** 2022-09-30 21:43 UTC
Labels: bug
