### ISSUE TITLE
[Bug] docker compose up -d error on building failed to calculate checksum

### ISSUE THREAD

**Issue by YuriyGavrilov** [apache/arrow-ballista#891] opened 2023-10-09 18:06 UTC
**Describe the bug**
There is an error when making `docker-compose up -d`

such as: 

```
[+] Running 3/3
 ! ballista-executor Warning                                                                                                       1.9s 
 ! ballista-client Warning                                                                                                         2.0s 
 ! ballista-scheduler Warning                                                                                                      2.0s 
[+] Building 0.8s (8/10)                                                                                                                
 => [ballista-scheduler internal] load build definition from ballista-scheduler.Dockerfile                                         0.0s
 => => transferring dockerfile: 1.45kB                                                                                             0.0s
 => [ballista-scheduler internal] load .dockerignore                                                                               0.0s
 => => transferring context: 255B                                                                                                  0.0s
 => [ballista-scheduler internal] load metadata for docker.io/library/ubuntu:22.04                                                 0.7s
 => [ballista-scheduler 1/6] FROM docker.io/library/ubuntu:22.04@sha256:9b8dec3bf938bc80fbe758d856e96fdfab5f56c39d44b0cff351e847b  0.0s
 => => resolve docker.io/library/ubuntu:22.04@sha256:9b8dec3bf938bc80fbe758d856e96fdfab5f56c39d44b0cff351e847bb1b01ea              0.0s
 => [ballista-scheduler internal] load build context                                                                               0.0s
 => => transferring context: 150B                                                                                                  0.0s
 => CACHED [ballista-scheduler 2/6] RUN apt-get update && apt-get install -y nginx netcat                                          0.0s
 => CACHED [ballista-scheduler 3/6] COPY target/release/ballista-scheduler /root/ballista-scheduler                                0.0s
 => ERROR [ballista-scheduler 4/6] COPY ballista/scheduler/ui/build /var/www/html                                                  0.0s
------
 > [ballista-scheduler 4/6] COPY ballista/scheduler/ui/build /var/www/html:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref d3d22851-6faa-49f5-8201-31f8b33b2996::2mfhqwfs4oi5oafy0gtj4slhw: "/ballista/scheduler/ui/build": not found
```

**To Reproduce**

`git clone ...`
`docker-compose up -d`

**Expected behavior**
docker build successfully 

**Additional context**

**Comment by ehenry2** [comment] 2023-10-09 20:12
What commit are you building from? 

(I noticed some of the tags used in the documentation for git clone, etc., are from older versions of Ballista. I was able to run docker-compose successfully from the latest commit on main branch)

You can run:

```git log -1```

**Comment by YuriyGavrilov** [comment] 2023-10-10 20:33
commit 1063e0a71badb4132e0a5b76c21c08d669e73161 (HEAD -> main, origin/main, origin/HEAD)
Author: r.4ntix <r.4ntix@gmail.com>
Date:   Wed Sep 20 04:51:45 2023 +0800

    Upgrade datafusion to 31.0.0 (#878)

**Comment by ehenry2** [comment] 2023-10-10 23:02
Thanks, yeah looks like the latest commit. I tried to replicate by cloning the repo and running docker compose but wasn't able to replicate the issue unfortunately. That error looks familiar when docker is expecting files in a particular location but there is none there. Perhaps the builder image has been cached? I'd suggest trying:

`docker-compose build --no-cache`

then trying running docker-compose up again

**Comment by andygrove** [comment] 2023-12-27 19:07
I have not been able to reproduce this issue, so I will close this. Feel free to re-open if this is still an issue for anyone.

**Closed by andygrove** 2023-12-27 19:07 UTC
Labels: bug

**Comment by YuriyGavrilov** [comment] 2023-12-27 20:14
ok @andygrove, may be someone else have the same. Will try to fix it but a bit later. 

fresh log the same:

```
(base) yuriygavrilov@MacBook-Pro-Yuriy arrow-ballista % docker-compose build --no-cache
[+] Building 1.3s (8/10)                                                                                                             docker:desktop-linux
 => [ballista-scheduler internal] load .dockerignore                                                                                                 0.0s
 => => transferring context: 255B                                                                                                                    0.0s
 => [ballista-scheduler internal] load build definition from ballista-scheduler.Dockerfile                                                           0.0s
 => => transferring dockerfile: 1.45kB                                                                                                               0.0s
 => [ballista-scheduler internal] load metadata for docker.io/library/ubuntu:22.04                                                                   0.9s
 => CANCELED [ballista-scheduler 1/6] FROM docker.io/library/ubuntu:22.04@sha256:6042500cf4b44023ea1894effe7890666b0c5c7871ed83a97c36c76ae560bb9b    0.0s
 => => resolve docker.io/library/ubuntu:22.04@sha256:6042500cf4b44023ea1894effe7890666b0c5c7871ed83a97c36c76ae560bb9b                                0.0s
 => => sha256:6042500cf4b44023ea1894effe7890666b0c5c7871ed83a97c36c76ae560bb9b 1.13kB / 1.13kB                                                       0.0s
 => => sha256:bbf3d1baa208b7649d1d0264ef7d522e1dc0deeeaaf6085bf8e4618867f03494 424B / 424B                                                           0.0s
 => [ballista-scheduler internal] load build context                                                                                                 0.0s
 => => transferring context: 150B                                                                                                                    0.0s
 => CACHED [ballista-scheduler 2/6] RUN apt-get update && apt-get install -y nginx netcat                                                            0.0s
 => ERROR [ballista-scheduler 3/6] COPY target/release/ballista-scheduler /root/ballista-scheduler                                                   0.0s
 => ERROR [ballista-scheduler 4/6] COPY ballista/scheduler/ui/build /var/www/html                                                                    0.0s
------
 > [ballista-scheduler 3/6] COPY target/release/ballista-scheduler /root/ballista-scheduler:
------
------
 > [ballista-scheduler 4/6] COPY ballista/scheduler/ui/build /var/www/html:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref d3d22851-6faa-49f5-8201-31f8b33b2996::mxeaby0sdtwlbluef18xwoe4h: "/ballista/scheduler/ui/build": not found
```

**Comment by Butch78** [comment] 2024-01-11 20:40
Unfortunately, I am having the same error:

```
failed to solve: failed to compute cache key: failed to calculate checksum of ref 62e32em3sauehttq0ma2lrz8f::vpscv3ywbjvnghsdj2p8nvo41: "/ballista/scheduler/ui/build": not found
```

Windows 11 WSL 2
